package com.yupi.template.model.dto.article;

import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * Shared workflow state for article generation.
 *
 * @author <a href="XXXX">呼哈设计</a>
 */
@Data
public class ArticleState implements Serializable {

    private static final long serialVersionUID = 1L;

    /** Task id. */
    private String taskId;

    /** Topic entered by the user. */
    private String topic;

    /** Optional user description. */
    private String userDescription;

    /** Selected article style. */
    private String style;

    /** Current backend phase. */
    private String phase;

    /** Current UI progress step. */
    private Integer progress;

    /** Raw streaming outline text before JSON becomes complete. */
    private String outlineRaw;

    /** Last known error message. */
    private String errorMessage;

    /** Candidate titles from agent 1. */
    private List<TitleOption> titleOptions;

    /** Selected title. */
    private TitleResult title;

    /** Outline generated by agent 2. */
    private OutlineResult outline;

    /** Article body generated by agent 3. */
    private String content;

    /** Image requirements generated by agent 4. */
    private List<ImageRequirement> imageRequirements;

    /** Cover image url. */
    private String coverImage;

    /** Generated images. */
    private List<ImageResult> images;

    /** Enabled image methods, null means unrestricted. */
    private List<String> enabledImageMethods;

    /** Final merged markdown content. */
    private String fullContent;

    @Data
    public static class TitleOption implements Serializable {
        private String mainTitle;
        private String subTitle;
    }

    @Data
    public static class TitleResult implements Serializable {
        private String mainTitle;
        private String subTitle;
    }

    @Data
    public static class OutlineResult implements Serializable {
        private List<OutlineSection> sections;
    }

    @Data
    public static class OutlineSection implements Serializable {
        private Integer section;
        private String title;
        private List<String> points;
    }

    @Data
    public static class ImageRequirement implements Serializable {
        private Integer position;
        private String type;
        private String sectionTitle;
        private String keywords;
        private String imageSource;
        private String prompt;
        private String placeholderId;
    }

    @Data
    public static class ImageResult implements Serializable {
        private Integer position;
        private String url;
        private String method;
        private String keywords;
        private String sectionTitle;
        private String description;
        private String placeholderId;
    }

    @Data
    public static class Agent4Result implements Serializable {
        private String contentWithPlaceholders;
        private List<ImageRequirement> imageRequirements;
    }
}
